// src/app/Home.tsx
import type React from "react";
import { Layout } from "./Layout";
import { Card, type CardProps } from "./components/Card";
import { Form } from "./components/Form";

export const Home: React.FC = () => {
	const cards: CardProps[] = [
		{
			title: "SOME FEATURES ARE MISSING",
			description: "But they'll be coming back soon:",
			items: ["Downloading images."],
		},
		{
			title: "THERE'S MORE COMING",
			description: "I'm working on more features, like:",
			items: [
				"A progress bar.",
				"Better peformance.",
				"Custom characters.",
				"AND SUPPORT FOR VIDEOS.",
			],
		},
	];

	return (
		<Layout>
			<div>
				<section>
					{cards.map((card) => (
						<Card key={card.title} {...card} />
					))}
				</section>
				<br />
				<section>
					<p className="mb-4 -mt-4">
						This is a website to convert any image to ASCII art. It allows you
						to upload an image and convert it to an ASCII text format in a
						heartbeat.
					</p>
					<p className="mb-6">
						At the moment, it supports common image formats like PNG, JPEG, JPG,
						and WEBP.
					</p>
				</section>
				<section>
					<Form />
				</section>
			</div>
		</Layout>
	);
};

// frontend/src/views/Home.vue
<script setup lang="ts">
import Callout from '../components/Callout.vue';
import FileForm from '../components/FileForm.vue';
</script>

<template>
    <Callout title="SOME FEATURES ARE MISSING">
        <p class="mb-2">But they'll be coming back soon:</p>
        <ul class="list-disc list-inside">
            <li>Downloading images.</li>
        </ul>
    </Callout>
    <Callout title="THERE'S MORE COMING:">
        <p class="mb-2">I'm working on more features, like:</p>
        <ul class="list-disc list-inside">
            <li>A progress bar.</li>
            <li>Better peformance.</li>
            <li>Custom characters.</li>
        </ul>
    </Callout>

    <p class="mb-4">
        This is a website to convert any image to ASCII art. It allows you to upload an image and
        convert it to an ASCII text format in a heartbeat.
    </p>
    <p class="mb-6">
        At the moment, it supports common image formats like PNG, JPEG, JPG, and WEBP.
    </p>

    <FileForm />
</template>
